### ISSUE TITLE
Results of ablation research

### ISSUE THREAD

**Issue by Hayleycat** [fengluodb/RangeSeg#11]
Thank you for your excellent work.
May I ask how the results of your ablation study were obtained. During training, there are many results from the validation set. Should we choose the best one? We look forward to your reply.
![6599345f8f281a4404126b069019698d](https://github.com/user-attachments/assets/4651c223-e956-4e5e-bd0a-4e0db962d29b)

**Comment by fengluodb** [comment]
Yes, I choose the best one.

**Comment by Hayleycat** [comment]
> Yes, I choose the best one.

Thank you for your reply. I have two more questions:
1、Through your code, I am able to train and reason normally using the Nuscenes dataset. But during evaluation, we encountered an index error as shown in the following figure. May I ask what the reason is.
![8C88169D3E60B4053854C4D110613E05](https://github.com/user-attachments/assets/01335dcf-c2c5-480a-bade-dff4c05e8d02)
2、In the code you provided, I used RTX4090 with an MIOU of 64 × 2048, which is even lower than that of 64 × 1024. In theory, the higher the resolution, the higher the accuracy. This is strange!
I am looking forward to your reply very much. It is very important to me.

**Comment by fengluodb** [comment]
I discovered a data type conversion error in infer.py when working with the NuScenes dataset. While I had previously implemented a fix locally, I unfortunately didn't commit it to GitHub and the fix was lost. I will create a new pull request to address this issue. Once I submit the PR, please feel free to test the fix.

**Comment by fengluodb** [comment]
Regarding the mIoU issue, could you please verify your training configuration settings?  You can also monitor the mIoU and other paramters changes  throughout the training process.

**Comment by Hayleycat** [comment]
> Regarding the mIoU issue, could you please verify your training configuration settings? You can also monitor the mIoU and other paramters changes throughout the training process.

Thank you very much for your prompt reply. This has been very helpful to me.

**Comment by Hayleycat** [comment]
> I discovered a data type conversion error in infer.py when working with the NuScenes dataset. While I had previously implemented a fix locally, I unfortunately didn't commit it to GitHub and the fix was lost. I will create a new pull request to address this issue. Once I submit the PR, please feel free to test the fix.

Hello! May I ask if you are available recently and when could you submit this pull request. Excuse me, thank you very much!

**Comment by fengluodb** [comment]
https://github.com/fengluodb/RangeSeg/pull/12

I have lose the dev environment. You can help me to fix the bug.

**Comment by Hayleycat** [comment]
> this is the #12.
> 
> I have lose the dev environment. You can help me to fix the bug.

Thank you. Oh, I see. But how can I help you? Do you need me to upload anything？

**Comment by fengluodb** [comment]
You can try it and reply me if have bugs.

**Comment by Hayleycat** [comment]
> You can try it and reply me if have bugs.

Thank you. I tried the fix code you provided and encountered this bug.
![bug](https://github.com/user-attachments/assets/59acee64-4f04-4987-aeb4-07acdc5d6456)

**Comment by Hayleycat** [comment]
> how much the points of label and pred. You also can debug the code find out the problem

number of points in predictions are 34720
number of points in label are 138880

**Comment by Hayleycat** [comment]
> how much the points of label and pred. You also can debug the code find out the problem

Thank you for your help. I changed the data type of pred to int32 and then rematched it to the format of 3D label, finally solving the problem.
![74 3](https://github.com/user-attachments/assets/02cde58a-2a2d-4dbb-8f2d-d47942503167)
Thank you again！！

**Comment by fengluodb** [comment]
Greatly. You can modified my pr to commit these change.
